### ISSUE TITLE
Read events from Kafka WAL

### ISSUE THREAD

**Issue by mariusandra** [PostHog/posthog-plugin-server#11]
On EE we currently process events directly in the web worker. We however also [emit a log](https://github.com/PostHog/posthog/blob/fae9fe5238dc0b605b49caee030275742b2b08ac/posthog/api/capture.py#L199-L209) with the processed event into kafka. 

The plugin server should be able to read this log like it is currently able to read celery and process the event from there.
Adding Event Ingestion (#10) directly into the plugin server will unlock running plugins on EE.

**Comment by Twixes** [comment]
Done in #70.
