### ISSUE TITLE
Remove backwards compatibility with setupTeam

### ISSUE THREAD

**Issue by yakkomajuri** [PostHog/posthog-plugin-server#2]
I was just looking at [this](https://github.com/PostHog/posthog-plugin-server/blob/6dbdd5c43655f9ea51fb824ae0b06aebf6536f75/src/vm.ts#L35) and thinking if we really need to be backwards compatible with `setupTeam`. The project is so early that I'm not sure this is justified. More of a nit really because it's just a matter of aesthetics.

**Comment by Twixes** [comment]
Agreed, would remove any compatibility stuff at this stage, unless it's absolutely needed. @mariusandra?

**Comment by mariusandra** [comment]
For sure!
