### ISSUE TITLE
Enable multiprocessing

### ISSUE THREAD

**Issue by Twixes** [PostHog/posthog-plugin-server#6]
Currently the server can only use 1 thread, even if the machine has for instance 8 cores and could handle 8 server threads at once, greatly improving performance under load.

**Comment by mariusandra** [comment]
After playing with this for a while, I think we should still implement threading within the worker :).

Currently the plugin server uses 4 celery connections, and possibly one more when we introduce scheduled tasks. We have a hard limit on Heroku and should try to limit the connections as much as possible. Three of these four connections could be shared between all forked workers, but only if we implement native threading/forking. With `pm2` (that we might use anyway) every worker requires 4 connections (and soon more with scheduled tasks), no exception. This might get heavy.

**Comment by mariusandra** [comment]
Another thing to consider. On Heroku we are getting the `WEB_CONCURRENCY` env variable from the [Python buildpack](https://github.com/heroku/heroku-buildpack-python/blob/main/vendor/WEB_CONCURRENCY.sh).

- Standard-1X (+Free, +Hobby) Dyno: 2
- Standard-2X Dyno: 4
- Performance-M Dyno: 8
- Performance-L Dyno: 11

In the NodeJS buildpack the values are however defined so:

![image](https://user-images.githubusercontent.com/53387/100297415-ec39bb00-2f8e-11eb-8217-32f9582ec32d.png)

Thus we can't really rely on this variable... and instead should divide it by two (except if it's 11, then we multiply by 2...?).

**Comment by mariusandra** [comment]
This is done!
